models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ../:/app
    ports:
      - "8001:8000"
    command: bash -c "python isaproject/manage.py makemigrations && python isaproject/manage.py migrate && python isaproject/manage.py loaddata isaproject/db.json && mod_wsgi-express start-server --working-directory isaproject/ --reload-on-changes isaproject/isaproject/wsgi.py"