models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ../:/app
    ports:
      - "8001:8000"
    command: bash -c "python /app/isaproject/manage.py makemigrations && python /app/isaproject/manage.py migrate && python /app/isaproject/manage.py loaddata /app/isaproject/db.json && mod_wsgi-express start-server --working-directory ../ --reload-on-changes /app/isaproject/isaproject/wsgi.py"
