# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='response',
            name='resp_timestamp',
        ),
    ]
