# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youbet', '0002_auto_20170921_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.NullBooleanField(),
        ),
    ]
